version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ssh
  webssh.cyrhades.fr:
    build: webssh
    ports:
    - ${PORT}:8888
  microroptor.cyrhades.fr:
    image: anssi/fcsc2022-pwn-microroptor:latest
    ports:
      - ${PORT_SSH}:4000